export const fields = {
  username: {
    label: 'User name',
    name: 'username',
    type: 'text',
    placeholder: 'User name*',
    title: '*The Name field must be more than 2 and less than 31 characters',
    required: true,
  },
  email: {
    label: 'Email',
    name: 'email',
    type: 'text',
    placeholder: 'Email*',
    title: '*Enter a valid email',
    required: true,
  },
  password: {
    label: 'Password',
    name: 'password',
    type: 'password',
    placeholder: 'Password*',
    title:
      '*The Password field must be more than 2 and less than 21 characters',
    required: true,
  },
  phone: {
    label: 'Phone',
    name: 'phone',
    type: 'tel',
    placeholder: 'Телефон*',
    title: '*Enter a valid phone number',
    required: true,
  },
  parentName: {
    label: 'Parent Name',
    name: 'parentName',
    type: 'text',
    placeholder: "Ваше ім'я*",
    title: '*Enter a valid Name',
    required: true,
  },
  childrenName: {
    label: 'Children Name',
    name: 'childrenName',
    type: 'text',
    placeholder: "Iм'я дитини*",
    title: '*Enter a valid Name',
    required: true,
  },
  subject: {
    label: 'Subject',
    name: 'subject',
    type: 'text',
    placeholder: 'Назва події',
    title: '*The Subject field must be more than 2 characters',
    required: true,
  },
  description: {
    name: 'description',
    type: 'text',
    placeholder: 'Опишіть подію',
    title: '*The Subject field must be more than 2 characters',
    required: true,
  },
  question: {
    name: 'question',
    type: 'text',
    placeholder: 'Задайте ваше питання',
    title: '*The Question field must be more than 2 characters',
    required: false,
  },
  nameOwnerReview: {
    label: 'Name of reviewer',
    name: 'nameOwnerReview',
    type: 'text',
    placeholder: 'ПІБ',
    title: '*The Name field must be more than 2 characters',
    required: true,
  },
  review: {
    label: 'Review',
    name: 'review',
    type: 'text',
    placeholder: 'Відгук',
    title: '*The Name field must be more than 2 characters',
    required: true,
  },
  dataSource: {
    label: 'Data Source',
    name: 'dataSource',
    type: 'text',
    placeholder: 'Джерело даних',
    title: '*The Data Source field must be more than 2 characters',
    required: false,
  },
  questions: {
    label: 'Questions',
    name: 'questions',
    type: 'text',
    placeholder: 'Ваше питання:',
    title: '*The Question field must be more than 10 characters',
    required: true,
  },
  answers: {
    label: 'Answers',
    name: 'answers',
    type: 'text',
    placeholder: 'Ваша відповідь на питання:',
    title: '*The Answers field must be more than 10 characters',
    required: true,
  },
};
